config/routes.rb
Rails.application.routes.draw do
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[create]
    resources :reviews, only: %i[create]
  end
  resources :bookmarks, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true

  def default_photo
    photo.key.nil? ? "placeholder" : photo.key
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  def find_bookmark(list)
    bookmarks.find_by list_id: list.id
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
    # default_photo
  end

  def show; end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :list_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for([list, bookmark]) do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Add a movie to a list</h1>
<%= render "form", list: @list, bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🍿 Mario Watchlist 🍿</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="navbar py-4">
    <div class="container">
      <div>
        <%= link_to "Watch lists", lists_path %>
      </div>
      <div>
        <%= link_to "My lists", lists_path %>
        <%= link_to "New list", new_list_path %>
      </div>
    </div>
  </div>

  <div style="margin-bottom: 100px">
    <%= yield %>
  </div>


  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<div class="banner mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80);">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>

<div class="container">

  <div class="row justify-content-center mb-4">
    <div class="col-10">
      <h2>My lists</h2>
    </div>
    <div class="col-2 d-flex align-items-center">
      <%= link_to "Create a movie list", new_list_path, class: "btn btn-success" %>
    </div>
  </div>

  <div class="row">

    <% @lists.each do |list| %>
      <div class="col-3">
        <div class="card-category position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.default_photo %>)">
          <%= link_to list.name, list_path(list), class: "stretched-link" %>
        </div>
      </div>
    <% end %>

  </div>

</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Create a new list</h1>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner mb-4" style="position: relative; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.default_photo %>);">
  <p class="btn btn-warning" style="opacity: 1; position: absolute; top: 10px; right: 10px"><%= @list.movies.count %> movies</p>
  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<div class="container">

  <div class="row justify-content-center mb-4">
    <div class="col-12">
      <h2>My movies</h2>
    </div>
  </div>

  <div class="row"> <!-- Beginning of the row -->

    <div class="col-8">

      <% if @list.movies == [] %>

        <p>Your list is empty. Wanna start adding films into your list?</p>

      <% else %>

        <div class="row">

          <% @list.movies.each do |movie| %>
            <div class="col-4">
              <div class="card-trip">
                <%= image_tag movie.poster_url %>

                <div class="card-trip-infos d-flex flex-column">

                  <div class="d-flex mb-2 justify-content-between align-items-center">
                    <h2><%= movie.title %></h2>
                    <div><%= movie.rating %> <i class="fas fa-star"></i></div>
                  </div>

                  <div>
                    <p><%= movie.overview %></p>
                  </div>
                </div>

                <div class="card-footer d-flex justify-content-between align-items-center">
                  <p><i class="fas fa-quote-left"></i> <%= movie.find_bookmark(@list).comment %></p>
                  <%= link_to "Delete", bookmark_path(movie.find_bookmark(@list)),
                                        method: :delete,
                                        data: { confirm: 'Are your sure?'}, class: "btn btn-danger"
                  %>
                </div>
              </div>
            </div>
          <% end %>

        </div>

      <% end %>

    </div>

    <div class="col-4">
      <div class="card p-5">
        <h2>Add a movie in this list</h2>
        <div class="card-body">
            <%= render "bookmarks/form", list: @list, bookmark: Bookmark.new %>
        </div>
      </div>
    </div>

  </div> <!-- End of the row -->

  <div class="row mt-4"> <!-- Beginning of the row -->

    <h2 class="mb-3">Reviews</h2>

      <% if @list.reviews == [] %>

      <p>There are no reviews yet. Wanna be the first?</p>

      <% else %>

        <ul class="list-group mb-4">

        <% @list.reviews.each do |review| %>

          <li class="list-group-item d-flex align-items-center">
            <p class="m-0 py-2"><%= review.content %></p>
          </li>

        <% end %>

      <% end %>

      </ul>

      <h4 class="mb-3">Add a review</h4>

      <%= render "reviews/form", list: @list, review: Review.new %>

  </div>

</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([list, review]) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>